### ISSUE TITLE
Expose bind and ingress addresses on Endpoint & Relation

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#179]
charms.reactive.Endpoint should expose network-get results, providing the bind and ingress addresses for the endpoint. It should also be exposed on the Relation in the same way.

For the 'cluster' endpoint, we get data that looks like this:
```$ juju run --unit=dse/1 -- network-get cluster --format=yaml```
```yaml
bind-addresses:
- macaddress: ""
  interfacename: ""
  addresses:
  - hostname: ""
    address: 10.55.60.255
    cidr: ""
ingress-addresses:
- 10.55.60.255
```
For a particular relation, we get a little more information:
```
$ juju run --unit=dse/1 -- network-get cluster --format=yaml -r cluster:2
```
```yaml
bind-addresses:
- macaddress: ""
  interfacename: ""
  addresses:
  - hostname: ""
    address: 10.55.60.255
    cidr: ""
egress-subnets:
- 10.55.60.255/32
ingress-addresses:
- 10.55.60.255
```

We could easily expose this as the data structure returned by charmhelpers.core.hookenv.network_get().

Less easy would be readable, usable accessors to the useful bits. Designing this needs some more thought.
