### ISSUE TITLE
charms.reactive.relations assumes the relation name is a key

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#28]
The RelationBase and Conversation model assumes that a relation name name is a key, rather than using the relation id + unit name. This will cause a reactive charm to fail, depending how the related service chooses to use it. For example, here is a metadata.yaml snippet from a client that stores its data in three separate silos:

```yaml
requires:
    session:
        interface: pgsql
    public:
        interface: pgsql
    confidential:
        interface: pgsql
```

On the client side, everything is fine. However, on the server side we have this:

```yaml
provides:
    db:
        interface: pgsql
```

If the client is related three times to the same server, which would be common for development and staging, then the reactive model fails as the relation name can not be used as a key to identify which of the three db interfaces is needed. The relation id must be used.
