### ISSUE TITLE
Merging layers with duplicate keys in metrics.yaml requires smarter tactic

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/charms.reactive#85]
This may be a two-part bug.

1. `charm build` doesn't appear to merge the contents of metrics.yaml, as is done with config.yaml.

2. Once that merge happens, we need to figure out the correct behavior. For example, if I have a metrics.yaml in two layers, layer-one and layer-two, thusly:

layer-one:
```yaml
metrics:
  users:
    type: gauge
    description: Number of users
    command: echo 1
  tokens:
    type: gauge
    description: Number of active tokens
    command: echo 0
```

layer-two:
```yaml
metrics:
  users:
    type: gauge
    description: Number of users
    command: echo 2
  tokens:
    type: gauge
    description: Number of active tokens
    command: echo 3
```

We're faced with an interesting dilemma. There is no guarantee that the users metric for layer-one if of the same type or measurement as layer-one. In this case, we would want each metric captured. So the question is how do we best maintain that uniqueness per layer?

I'd considered automatically adding some kind of namespacing to the metric name, i.e., layer-one.users and layer-two.users, but that's problematic, because we're changing the expectation of what the metric name will be (i.e., to the operator/consumer trying to ingest the metrics).

I suspect the "best" way to handle this would be to display a warning or error when `charm build` is executed and a duplication is detected. The charm consuming the layer originating a metric name should be responsible for avoiding collisions.
